# Generated by Django 3.2.7 on 2021-09-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('profilePic', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=1000)),
                ('starCount', models.IntegerField()),
                ('repoCount', models.IntegerField()),
                ('followerCount', models.IntegerField()),
                ('contributionCount', models.IntegerField(default=0)),
            ],
        ),
    ]
