# Generated by Django 3.1.1 on 2021-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('profilePic', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50, null=True)),
                ('bio', models.CharField(max_length=1000, null=True)),
                ('starCount', models.IntegerField()),
                ('repoCount', models.IntegerField()),
                ('followerCount', models.IntegerField()),
                ('contributionCount', models.IntegerField(default=0)),
                ('groupName', models.CharField(
                    default='HackerNoobs', max_length=50, null=True)),
                ('namegroupid', models.CharField(
                    default='name_HackerNoobs', max_length=100, null=True)),
            ],
        ),
    ]
