# Generated by Django 3.1.1 on 2021-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitsclub', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='nandakishormapi@gmail.com', max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='githubuserId',
            field=models.CharField(default='nandakishormpai', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
